language: node_js
before_script:
- make build
before_deploy:
- make archive
deploy:
  provider: releases
  api_key:
    secure: Ijc/h2idPc2TI6mLhk5bFFYpa6LTxTQIiXcXgD0o5esY6Gruva1O4ze3HvWxiSMH2pFj3UfPfsn0cOAhD/MQGTwrhsW73TiZd5jjV0+e1Jb6W2dpFhiOSUdDNX3NCvYWqsiE0HMBaqVVmfRPGt0xe9MCu/vEq4ahxOI/oleEQlc=
  file: build/PostmanImporter.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: luckymarmot/Paw-PostmanImporter
